swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# method supported by the server application


get:
  operationId: peoplelist.people.read_all
  tags:
    - People
  summary: Read the entire set of people, sorted by person_id
  description: Read the entire set of people, sorted by person_id 
  responses:
    200:
      description: Successfully read people set operation
      schema:
        type: array
        items:
          properties:
            person_id:
              type: string
              description: Id of the person
            fname:
              type: string
              description: First name of the person
            lname:
              type: string
              description: Last name of the person
            timestamp:
              type: string
              description: Creation/Update timestamp of the person

post:
  operationId: peoplelist.people.create
  tags:
    - People
  summary: Create a person
  description: Create a new person
  parameters:
    - name: person
      in: body
      description: Person to create
      required: True
      schema:
        type: object
        properties:
          fname:
            type: string
            description: First name of person to create
          lname:
            type: string
            description: Last name of person to create
  responses:
    201:
      description: Successfully created person
      schema:
        properties:
          person_id:
            type: string
            description: Id of the person
          fname:
            type: string
            description: First name of the person
          lname:
            type: string
            description: Last name of the person
          timestamp:
            type: string
            description: Creation/Update timestamp of the person record

